export const SET_ORGANISATION_LIST = 'SET_ORGANISATION_LIST';
export const SET_CREATORS_LIST = 'SET_CREATORS_LIST';
export const SET_DAO = 'SET_DAO';
export const SET_ACTIVE_EOS_ACCOUNT = 'SET_ACTIVE_EOS_ACCOUNT'
export const SET_DAOTOKENS_LIST = 'SET_DAOTOKENS_LIST';
